<?php
  require_once './includes/variables.php';
  session_start();
  if(!$_SESSION["id"]){
    header("location:".preg_replace('/[\/]$/', '', $siteURL)."/login");
  }
  $_SESSION["id"] = 10;
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>New Sheet</title>
    <link href='http://fonts.googleapis.com/css?family=Krona+One' rel='stylesheet' type='text/css'>
    <link href="./extra/mine.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="./extra/jQuery.js"></script>
    <script type="text/javascript" src="./extra/json2.js"></script>
    <script type="text/javascript" src="./extra/js.js"></script>
  </head>
  <body>
    <?php
      include "./includes/controls.php";
    ?>
    <div class="bodyContainer">
      <a name='top'></a>
      <?php
        include $jumpMenu;
      ?>
      <h2 id="characterInfo"><span class="close">X</span>Character Info:</h2>
      <?php
        include "./modules/character.php";
        include $jumpMenu;
      ?>
      <a name='attributes'></a>
      <h2 id="attributes"><span class="close">X</span>Attributes:</h2>
      <?php
        include "./modules/attributes.php";
        include $jumpMenu;
      ?>
      <a name='derived_Traits'></a>
      <h2 id="derivedTraits"><span class="close">X</span>Derived Traits:</h2>
      <?php
        include "./modules/derived_traits.php";
        include $jumpMenu;
      ?>
      <a name='skills_and_specialties'></a>
      <h2 id="skillsSpecialties"><span class="close">X</span>Skills and Specialties:</h2>
      <?php
        include "./modules/skills_specialties.php";
        include $jumpMenu;
      ?>
      <div class='column'>
        <a name='equipment'></a>
        <h2 id="equipment"><span class="close">X</span>Equipment:</h2>
        <?php
          include "./modules/equipment.php";
          include $jumpMenu;
        ?>
        <a name='info'></a>
        <h2 id="info"><span class="close">X</span>Info:</h2>
        <?php
          include "./modules/info.php";
          include $jumpMenu;
        ?>
        <a name='dice'></a>
        <h2 id="dice"><span class="close">X</span>Dice:</h2>
        <?php
          include "./modules/dice.php";
        ?>
      </div>
      <div class='column'>
        <div class='column'>
          <a name='complications'></a>
          <h2 class="comp_asset" id="comp"><span class="close">X</span>Complications:</h2>
          <?php
            $comp_asset = 'complications';
            include "./modules/comp_asset.php";
          ?>
        </div>
        <div class='column'>
          <a name='assets'></a>
          <h2 class="comp_asset" id="asset"><span class="close">X</span>Assets:</h2>
          <?php
            $comp_asset = 'assets';
            include "./modules/comp_asset.php";
          ?>
        </div>
      </div>
      <?php
        include $jumpMenu;
      ?>
      <div id='saveMessage' class='saveMessage'>Saved</div>
      <a name='bottom'></a>
    </div>
  </body>
</html>