<?php
  require_once './includes/variables.php';
  session_start();
?>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Serenity Character Sheet</title>
    <link href="http://fonts.googleapis.com/css?family=Almendra+SC|Krona+One" rel="stylesheet" type="text/css">
    <link href="./extra/universal.css" rel="stylesheet" type="text/css" />
    <link href="./extra/character_sheet.css" rel="stylesheet" type="text/css" />
    <script src="./extra/jQuery.js"></script>
    <script type="text/javascript" src="./extra/json2.js"></script>
    <script type="text/javascript" src="./extra/character_sheet.js"></script>
<?php if(!$_SESSION['id']) { ?>
    <link href="./extra/sign.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="./extra/sign.js"></script>
<?php } ?>
  </head>
  <body id="top">
    <?php
    if(!$_SESSION['id']) {
      include_once './sign/readme.php';
      include_once './sign/in.php';
      include_once './sign/up.php';
      include_once './sign/note.php';
    } else {
      include './includes/controls.php';
      include_once $jumpMenu;
    ?>
    <div class="bodyContainer">
      <div class="sheetTitle">
        Serenity Character Sheet
      </div>
      <?php _jumpMenu(); ?>
      <h2 id="characterInfo"><span class="close"><span class="arrow"></span></span>Character Info:</h2>
      <?php
        include './modules/character.php';
        _jumpMenu();
      ?>
      <h2 id="attributes"><span class="close"><span class="arrow"></span></span>Attributes:</h2>
      <?php
        include './modules/attributes.php';
        _jumpMenu();
      ?>
      <h2 id="derivedTraits"><span class="close"><span class="arrow"></span></span>Derived Traits:</h2>
      <?php
        include './modules/derived_traits.php';
        _jumpMenu();
      ?>
      <h2 id="skillsSpecialties"><span class="close"><span class="arrow"></span></span>Skills and Specialties:</h2>
      <?php
        include './modules/skills_specialties.php';
        _jumpMenu();
      ?>
      <div class="column">
        <h2 id="equipment"><span class="close"><span class="arrow"></span></span>Equipment:</h2>
        <?php
          include './modules/equipment.php';
          _jumpMenu();
        ?>
        <h2 id="info"><span class="close"><span class="arrow"></span></span>Info:</h2>
        <?php
          include './modules/info.php';
          _jumpMenu();
        ?>
        <h2 id="dice"><span class="close"><span class="arrow"></span></span>Dice:</h2>
        <?php
          include './modules/dice.php';
        ?>
      </div>
      <div class="column">
        <div class="column">
          <h2 class="comp_asset" id="complications"><span class="close"><span class="arrow"></span></span>Complications:</h2>
          <?php
            $comp_asset = 'complications';
            include './modules/comp_asset.php';
          ?>
        </div>
        <div class="column">
          <h2 class="comp_asset" id="assets"><span class="close"><span class="arrow"></span></span>Assets:</h2>
          <?php
            $comp_asset = 'assets';
            include './modules/comp_asset.php';
          ?>
        </div>
      </div>
      <div id="saveMessage" class="saveMessage">Saved</div>
      <a class="signOut" href="<?= $siteURL ?>signout">Sign out</a>
      <?php _jumpMenu(); ?>
      <div id="bottom"></div>
    </div>
    <?php } ?>
    <script>
      var mykey="<?= $_SESSION['hash']; ?>";
<?php if($_SESSION['id'] === '27') { ?>
      jQ(window).on('beforeunload', function() {
        sheet.functions.unload();
      });
<?php }?>
    </script>
  </body>
</html>