<?php
	session_start();
  
	if($_SESSION["id"]){
		header("location:/new/sheet/beta/");
	}
	require_once "../includes/log-sign_in.php";
  require_once '../includes/variables.php';
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Login - Character Sheet</title>
<script type="text/javascript" src="../extra/jQuery.js"></script>
<script type="text/javascript" src="../extra/js.js"></script>
</head>

<body>
  <form id="LogSign" action="<?= preg_replace('/(\?id\=[0-9]+)/', '', $siteURL); ?>" method="post">
    <input type="hidden" id="frmUName" name="frmUName" value="" />
    <input type="hidden" id="frmEMail" name="frmEMail" value="" />
    <input type="hidden" id="frmPWord" name="frmPWord" value="" />
    <input type="hidden" id="frmLogSign" name="frmLogSign" value="" />
  </form>

<h1>Log In</h1>
<input type="hidden" value="User" id="UName_L" />
<?php
  if (!is_null($_GET["id"])) {
		echo "<h2>Please sign in.</h2>\n";
	}

	if ($LogSign == "L" || is_null($LogSign)) {
		echo "<label class=\"";
		if ($EMailVerify == 1) {
			echo "ErrorText";
		} else {
			echo "GoodText";
		}
		echo "\" id=\"EMail-L\">Your Email</label>:<input type=\"text\" value=\"" . $EMail . "\" id=\"EMail_L\" />\n";

		echo "<label class=\"";
		if ($PWordVerify == 1) {
			echo "ErrorText";
		} else {
			echo "GoodText";
		}
		echo "\" id=\"PWord-L\">Your Password</label>:<input type=\"password\" value=\"" . $PWord . "\" id=\"PWord_L\" />\n";
		echo "<input type=\"submit\" value=\"Log In\" onclick=\"LogSign(0)\" />\n";
	}
?>
<hr />
<h1>Sign Up</h1>
<?php
	if (!is_null($_GET["id"])) {
		echo "<h2>Registation complete, you should be geting an email shortly.</h2>\n";
	}
	if ($LogSign == "S" || is_null($LogSign)) {
		echo "<label class=\"";
		if ($UNameVerify == 1) {
			echo "ErrorText";
		} else {
			echo "GoodText";
		}
		echo "\" id=\"UName-S\">Your Name</label>:<input type=\"text\" value=\"" . $UName . "\" id=\"UName_S\" />\n";

		echo "<label class=\"";
		if ($EMailVerify == 1) {
			echo "ErrorText";
		} else {
			echo "GoodText";
		}
		echo "\" id=\"EMail-S\">Your Email</label>:<input type=\"text\" value=\"" . $EMail . "\" id=\"EMail_S\" />\n";

		echo "<label class=\"";
		if ($PWordVerify == 1) {
			echo "ErrorText";
		} else {
			echo "GoodText";
		}
		echo "\" id=\"PWord-S\">Your Password</label>:<input type=\"password\" value=\"" . $PWord . "\" id=\"PWord_S\" />\n";
		echo "<input type=\"submit\" value=\"Sign Up\" onclick=\"LogSign(1)\" />\n";
	}
?>
</body>
</html>
